# Validate lint, build, and tests on PR
name: Push Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: npm ci, lint, test
        run: |
          cp .env.sample .env
          npm ci
          npm run lint
          npm run test

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Write .env file
        run: echo ${{ secrets.ENV_FILE_PROD }} | base64 -d > .env
      - name: GCP Authentication
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: List Functions
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        with:
          args: functions list
      - name: Deploy Function - webhooks
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        with:
          args: functions deploy webhooks --runtime nodejs10 --trigger-http --entry-point hooks
